const flags = [
  { code: "ad", name: "Andorra" },
  { code: "ae", name: "Emiratos Árabes Unidos" },
  { code: "af", name: "Afganistán" },
  { code: "ag", name: "Antigua y Barbuda" },
  { code: "ai", name: "Anguila" },
  { code: "al", name: "Albania" },
  { code: "am", name: "Armenia" },
  { code: "ao", name: "Angola" },
  { code: "aq", name: "Antártida" },
  { code: "ar", name: "Argentina" },
  { code: "as", name: "Samoa Americana" },
  { code: "at", name: "Austria" },
  { code: "au", name: "Australia" },
  { code: "aw", name: "Aruba" },
  { code: "ax", name: "Islas Åland" },
  { code: "az", name: "Azerbaiyán" },
  { code: "ba", name: "Bosnia y Herzegovina" },
  { code: "bb", name: "Barbados" },
  { code: "bd", name: "Bangladés" },
  { code: "be", name: "Bélgica" },
  { code: "bf", name: "Burkina Faso" },
  { code: "bg", name: "Bulgaria" },
  { code: "bh", name: "Baréin" },
  { code: "bi", name: "Burundi" },
  { code: "bj", name: "Benín" },
  { code: "bl", name: "San Bartolomé" },
  { code: "bm", name: "Bermudas" },
  { code: "bn", name: "Brunéi" },
  { code: "bo", name: "Bolivia" },
  { code: "bq", name: "Caribe Neerlandés" },
  { code: "br", name: "Brasil" },
  { code: "bs", name: "Bahamas" },
  { code: "bt", name: "Bután" },
  { code: "bv", name: "Isla Bouvet" },
  { code: "bw", name: "Botsuana" },
  { code: "by", name: "Bielorrusia" },
  { code: "bz", name: "Belice" },
  { code: "ca", name: "Canadá" },
  { code: "cc", name: "Islas Cocos (Keeling)" },
  { code: "cd", name: "República Democrática del Congo" },
  { code: "cf", name: "República Centroafricana" },
  { code: "cg", name: "República del Congo" },
  { code: "ch", name: "Suiza" },
  { code: "ci", name: "Costa de Marfil" },
  { code: "ck", name: "Islas Cook" },
  { code: "cl", name: "Chile" },
  { code: "cm", name: "Camerún" },
  { code: "cn", name: "China" },
  { code: "co", name: "Colombia" },
  { code: "cr", name: "Costa Rica" },
  { code: "cu", name: "Cuba" },
  { code: "cv", name: "Cabo Verde" },
  { code: "cw", name: "Curazao" },
  { code: "cx", name: "Isla de Navidad" },
  { code: "cy", name: "Chipre" },
  { code: "cz", name: "Chequia" },
  { code: "de", name: "Alemania" },
  { code: "dj", name: "Yibuti" },
  { code: "dk", name: "Dinamarca" },
  { code: "dm", name: "Dominica" },
  { code: "do", name: "República Dominicana" },
  { code: "dz", name: "Argelia" },
  { code: "ec", name: "Ecuador" },
  { code: "ee", name: "Estonia" },
  { code: "eg", name: "Egipto" },
  { code: "eh", name: "Sahara Occidental" },
  { code: "er", name: "Eritrea" },
  { code: "es", name: "España" },
  { code: "et", name: "Etiopía" },
  { code: "fi", name: "Finlandia" },
  { code: "fj", name: "Fiyi" },
  { code: "fk", name: "Islas Malvinas" },
  { code: "fm", name: "Micronesia" },
  { code: "fo", name: "Islas Feroe" },
  { code: "fr", name: "Francia" },
  { code: "ga", name: "Gabón" },
  { code: "gb", name: "Reino Unido" },
  { code: "gb-eng", name: "Inglaterra" },
  { code: "gb-nir", name: "Irlanda del Norte" },
  { code: "gb-sct", name: "Escocia" },
  { code: "gb-wls", name: "Gales" },
  { code: "gd", name: "Granada" },
  { code: "ge", name: "Georgia" },
  { code: "gf", name: "Guayana Francesa" },
  { code: "gg", name: "Guernsey" },
  { code: "gh", name: "Ghana" },
  { code: "gi", name: "Gibraltar" },
  { code: "gl", name: "Groenlandia" },
  { code: "gm", name: "Gambia" },
  { code: "gn", name: "Guinea" },
  { code: "gp", name: "Guadalupe" },
  { code: "gq", name: "Guinea Ecuatorial" },
  { code: "gr", name: "Grecia" },
  { code: "gs", name: "Islas Georgias del Sur y Sandwich del Sur" },
  { code: "gt", name: "Guatemala" },
  { code: "gu", name: "Guam" },
  { code: "gw", name: "Guinea-Bisáu" },
  { code: "gy", name: "Guyana" },
  { code: "hk", name: "Hong Kong" },
  { code: "hm", name: "Islas Heard y McDonald" },
  { code: "hn", name: "Honduras" },
  { code: "hr", name: "Croacia" },
  { code: "ht", name: "Haití" },
  { code: "hu", name: "Hungría" },
  { code: "id", name: "Indonesia" },
  { code: "ie", name: "Irlanda" },
  { code: "il", name: "Israel" },
  { code: "im", name: "Isla de Man" },
  { code: "in", name: "India" },
  { code: "io", name: "Territorio Británico del Océano Índico" },
  { code: "iq", name: "Irak" },
  { code: "ir", name: "Irán" },
  { code: "is", name: "Islandia" },
  { code: "it", name: "Italia" },
  { code: "je", name: "Jersey" },
  { code: "jm", name: "Jamaica" },
  { code: "jo", name: "Jordania" },
  { code: "jp", name: "Japón" },
  { code: "ke", name: "Kenia" },
  { code: "kg", name: "Kirguistán" },
  { code: "kh", name: "Camboya" },
  { code: "ki", name: "Kiribati" },
  { code: "km", name: "Comoras" },
  { code: "kn", name: "San Cristóbal y Nieves" },
  { code: "kp", name: "Corea del Norte" },
  { code: "kr", name: "Corea del Sur" },
  { code: "kw", name: "Kuwait" },
  { code: "ky", name: "Islas Caimán" },
  { code: "kz", name: "Kazajistán" },
  { code: "la", name: "Laos" },
  { code: "lb", name: "Líbano" },
  { code: "lc", name: "Santa Lucía" },
  { code: "li", name: "Liechtenstein" },
  { code: "lk", name: "Sri Lanka" },
  { code: "lr", name: "Liberia" },
  { code: "ls", name: "Lesoto" },
  { code: "lt", name: "Lituania" },
  { code: "lu", name: "Luxemburgo" },
  { code: "lv", name: "Letonia" },
  { code: "ly", name: "Libia" },
  { code: "ma", name: "Marruecos" },
  { code: "mc", name: "Mónaco" },
  { code: "md", name: "Moldavia" },
  { code: "me", name: "Montenegro" },
  { code: "mf", name: "San Martín" },
  { code: "mg", name: "Madagascar" },
  { code: "mh", name: "Islas Marshall" },
  { code: "mk", name: "Macedonia del Norte" },
  { code: "ml", name: "Malí" },
  { code: "mm", name: "Birmania" },
  { code: "mn", name: "Mongolia" },
  { code: "mo", name: "Macao" },
  { code: "mp", name: "Islas Marianas del Norte" },
  { code: "mq", name: "Martinica" },
  { code: "mr", name: "Mauritania" },
  { code: "ms", name: "Montserrat" },
  { code: "mt", name: "Malta" },
  { code: "mu", name: "Mauricio" },
  { code: "mv", name: "Maldivas" },
  { code: "mw", name: "Malaui" },
  { code: "mx", name: "México" },
  { code: "my", name: "Malasia" },
  { code: "mz", name: "Mozambique" },
  { code: "na", name: "Namibia" },
  { code: "nc", name: "Nueva Caledonia" },
  { code: "ne", name: "Níger" },
  { code: "nf", name: "Isla Norfolk" },
  { code: "ng", name: "Nigeria" },
  { code: "ni", name: "Nicaragua" },
  { code: "nl", name: "Países Bajos" },
  { code: "no", name: "Noruega" },
  { code: "np", name: "Nepal" },
  { code: "nr", name: "Nauru" },
  { code: "nu", name: "Niue" },
  { code: "nz", name: "Nueva Zelanda" },
  { code: "om", name: "Omán" },
  { code: "pa", name: "Panamá" },
  { code: "pe", name: "Perú" },
  { code: "pf", name: "Polinesia Francesa" },
  { code: "pg", name: "Papúa Nueva Guinea" },
  { code: "ph", name: "Filipinas" },
  { code: "pk", name: "Pakistán" },
  { code: "pl", name: "Polonia" },
  { code: "pm", name: "San Pedro y Miquelón" },
  { code: "pn", name: "Islas Pitcairn" },
  { code: "pr", name: "Puerto Rico" },
  { code: "ps", name: "Palestina" },
  { code: "pt", name: "Portugal" },
  { code: "pw", name: "Palaos" },
  { code: "py", name: "Paraguay" },
  { code: "qa", name: "Catar" },
  { code: "re", name: "Reunión" },
  { code: "ro", name: "Rumanía" },
  { code: "rs", name: "Serbia" },
  { code: "ru", name: "Rusia" },
  { code: "rw", name: "Ruanda" },
  { code: "sa", name: "Arabia Saudita" },
  { code: "sb", name: "Islas Salomón" },
  { code: "sc", name: "Seychelles" },
  { code: "sd", name: "Sudán" },
  { code: "se", name: "Suecia" },
  { code: "sg", name: "Singapur" },
  { code: "sh", name: "Santa Elena" },
  { code: "si", name: "Eslovenia" },
  { code: "sj", name: "Svalbard y Jan Mayen" },
  { code: "sk", name: "Eslovaquia" },
  { code: "sl", name: "Sierra Leona" },
  { code: "sm", name: "San Marino" },
  { code: "sn", name: "Senegal" },
  { code: "so", name: "Somalia" },
  { code: "sr", name: "Surinam" },
  { code: "ss", name: "Sudán del Sur" },
  { code: "st", name: "Santo Tomé y Príncipe" },
  { code: "sv", name: "El Salvador" },
  { code: "sx", name: "Sint Maarten" },
  { code: "sy", name: "Siria" },
  { code: "sz", name: "Esuatini" },
  { code: "tc", name: "Islas Turcas y Caicos" },
  { code: "td", name: "Chad" },
  { code: "tf", name: "Territorios Australes Franceses" },
  { code: "tg", name: "Togo" },
  { code: "th", name: "Tailandia" },
  { code: "tj", name: "Tayikistán" },
  { code: "tk", name: "Tokelau" },
  { code: "tl", name: "Timor Oriental" },
  { code: "tm", name: "Turkmenistán" },
  { code: "tn", name: "Túnez" },
  { code: "to", name: "Tonga" },
  { code: "tr", name: "Turquía" },
  { code: "tt", name: "Trinidad y Tobago" },
  { code: "tv", name: "Tuvalu" },
  { code: "tw", name: "Taiwán" },
  { code: "tz", name: "Tanzania" },
  { code: "ua", name: "Ucrania" },
  { code: "ug", name: "Uganda" },
  { code: "um", name: "Islas Ultramarinas Menores de EE. UU." },
  { code: "us", name: "Estados Unidos" },
  { code: "uy", name: "Uruguay" },
  { code: "uz", name: "Uzbekistán" },
  { code: "va", name: "Ciudad del Vaticano" },
  { code: "vc", name: "San Vicente y las Granadinas" },
  { code: "ve", name: "Venezuela" },
  { code: "vg", name: "Islas Vírgenes Británicas" },
  { code: "vi", name: "Islas Vírgenes de EE. UU." },
  { code: "vn", name: "Vietnam" },
  { code: "vu", name: "Vanuatu" },
  { code: "wf", name: "Wallis y Futuna" },
  { code: "ws", name: "Samoa" },
  { code: "xk", name: "Kosovo" },
  { code: "ye", name: "Yemen" },
  { code: "yt", name: "Mayotte" },
  { code: "za", name: "Sudáfrica" },
  { code: "zm", name: "Zambia" },
  { code: "zw", name: "Zimbabue" }
];


let currentFlag = null;

function showRandomFlag() {
  currentFlag = flags[Math.floor(Math.random() * flags.length)];
  document.getElementById("flag-img").src = `flags/${currentFlag.code}.png`;
  hideTooltip();
}

function showTooltip() {
  if (!currentFlag) return;
  const btn = document.getElementById("show-name");
  const tooltip = document.getElementById("flag-tooltip");
  tooltip.textContent = currentFlag.name;
  tooltip.style.display = "inline-block";
  // Position tooltip below button
  const rect = btn.getBoundingClientRect();
  tooltip.style.left = rect.left + window.scrollX + rect.width / 2 - tooltip.offsetWidth / 2 + "px";
  tooltip.style.top = rect.bottom + window.scrollY + 8 + "px";
}

function hideTooltip() {
  const tooltip = document.getElementById("flag-tooltip");
  tooltip.style.display = "none";
}

document.addEventListener("DOMContentLoaded", () => {
  showRandomFlag();
  document.getElementById("show-name").addEventListener("click", showTooltip);
  document.getElementById("show-name").addEventListener("mouseleave", hideTooltip);
});
